//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwapDeals.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Advertisements = new HashSet<Advertisement>();
        }
    
        public int ProductID { get; set; }
        
        [Display(Name ="Product Name")]
        [DataType(DataType.Text)]
        public string ProductName { get; set; }
        
        [Display(Name = "Product Price")]
        public decimal ProductPrice { get; set; }
        
        [Display(Name = "Product Details")]
        [DataType(DataType.Text)]
        public string ProductDetails { get; set; }
        
        [Display(Name = "Product Category")]
        [DataType(DataType.Text)]
        public string ProductCategory { get; set; }
        
        [Display(Name = "Brand")]
        [DataType(DataType.Text)]
        public string ProductBrand { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advertisement> Advertisements { get; set; }
    }
}
